[package]
name = "Command_findtext"
version = "0.1.0"
authors = ["Caleb <farmingtoncardinals24@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
#nix = "19.0"
